# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Katherine McAuliffe
email: kgmcauliffe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Katherine McAuliffe, engineer, extrovert, and events manager 
  who codes, crafts, and games on the side. Find out more about her voice acting 
  career, tech career, and personal projects on this site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codemonkey9000.gitpages.io" # the base hostname & protocol for your site
twitter_username: katmccat
github_username:  codemonkey9000

# Build settings
markdown: kramdown
